"use client";
import { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import { apiStartExam, apiSubmitExam, apiExamHistory } from "@/lib/api";
import type { ExamConfig, ExamAttempt, ExamResult, ExamDomain } from "@/types";
import { fmtSecs, cn } from "@/lib/utils";
import { useQuery } from "@tanstack/react-query";
import ReactMarkdown from "react-markdown";

const DOMAINS: ExamDomain[] = ["DSA","OOPS/DBMS/OS","Aptitude","Verbal","System Design","HR Behavioral"];

type Phase = "config" | "exam" | "result";

export default function ExamPage() {
  const [phase, setPhase] = useState<Phase>("config");
  const [config, setConfig] = useState<ExamConfig>({
    domains: ["DSA","Aptitude"], num_questions: 20,
    duration_minutes: 30, difficulty: "mixed",
  });
  const [attempt, setAttempt] = useState<ExamAttempt | null>(null);
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [currentQ, setCurrentQ] = useState(0);
  const [timeLeft, setTimeLeft] = useState(0);
  const [tabSwitches, setTabSwitches] = useState(0);
  const [result, setResult] = useState<ExamResult | null>(null);
  const [loading, setLoading] = useState(false);
  const startTime = useRef<number>(0);
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  const { data: history = [] } = useQuery({ queryKey: ["exam-history"], queryFn: apiExamHistory });

  // Tab visibility anti-cheat
  useEffect(() => {
    if (phase !== "exam") return;
    const handler = () => {
      if (document.hidden) {
        setTabSwitches(n => n + 1);
        toast.warning(`⚠️ Tab switch detected! (${tabSwitches + 1}x) Penalty applied.`);
      }
    };
    document.addEventListener("visibilitychange", handler);
    return () => document.removeEventListener("visibilitychange", handler);
  }, [phase, tabSwitches]);

  // Countdown timer
  useEffect(() => {
    if (phase !== "exam" || !attempt) return;
    setTimeLeft(config.duration_minutes * 60);
    startTime.current = Date.now();
    timerRef.current = setInterval(() => {
      setTimeLeft(t => {
        if (t <= 1) { clearInterval(timerRef.current!); handleSubmit(true); return 0; }
        return t - 1;
      });
    }, 1000);
    return () => clearInterval(timerRef.current!);
  }, [phase, attempt]);

  async function startExam() {
    if (config.domains.length === 0) { toast.error("Select at least one domain"); return; }
    setLoading(true);
    try {
      const a = await apiStartExam(config);
      setAttempt(a);
      setAnswers({});
      setCurrentQ(0);
      setTabSwitches(0);
      setPhase("exam");
    } catch { toast.error("Failed to start exam — is the backend running?"); }
    finally { setLoading(false); }
  }

  async function handleSubmit(autoSubmit = false) {
    if (!attempt) return;
    clearInterval(timerRef.current!);
    const timeTaken = Math.floor((Date.now() - startTime.current) / 1000);
    setLoading(true);
    try {
      const r = await apiSubmitExam(attempt.attempt_id, answers, timeTaken, tabSwitches);
      setResult(r);
      setPhase("result");
      if (autoSubmit) toast.info("⏰ Time's up! Exam auto-submitted.");
    } catch { toast.error("Submission failed"); }
    finally { setLoading(false); }
  }

  const toggleDomain = (d: ExamDomain) =>
    setConfig(c => ({
      ...c, domains: c.domains.includes(d) ? c.domains.filter(x => x !== d) : [...c.domains, d]
    }));

  // ── CONFIG PHASE ─────────────────────────────────────────────────────────
  if (phase === "config") return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h1 className="text-2xl font-bold text-white">📝 Practice Exam</h1>
        <p className="text-gray-400 text-sm mt-1">Adaptive MCQs generated by Gemini AI — anti-cheat enabled.</p>
      </div>

      <div className="glass-card p-6 space-y-5">
        <div>
          <label className="block text-xs text-gray-400 mb-2">Select Domains</label>
          <div className="flex flex-wrap gap-2">
            {DOMAINS.map(d => (
              <button key={d} onClick={() => toggleDomain(d)}
                className={cn("px-3 py-1.5 rounded-lg text-xs font-medium border transition-all",
                  config.domains.includes(d) ? "bg-brand border-brand text-white" : "border-surface-border text-gray-400 hover:border-brand/50")}>
                {d}
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-xs text-gray-400 mb-1.5">Number of Questions</label>
            <select value={config.num_questions}
              onChange={e => setConfig(c => ({ ...c, num_questions: +e.target.value }))}
              className="input-dark">
              {[10, 15, 20, 30, 40, 50].map(n => <option key={n} value={n}>{n} Questions</option>)}
            </select>
          </div>
          <div>
            <label className="block text-xs text-gray-400 mb-1.5">Duration</label>
            <select value={config.duration_minutes}
              onChange={e => setConfig(c => ({ ...c, duration_minutes: +e.target.value }))}
              className="input-dark">
              {[15, 20, 30, 45, 60, 90].map(n => <option key={n} value={n}>{n} minutes</option>)}
            </select>
          </div>
        </div>

        <div>
          <label className="block text-xs text-gray-400 mb-1.5">Difficulty</label>
          <div className="flex gap-2">
            {(["easy","medium","hard","mixed"] as const).map(d => (
              <button key={d} onClick={() => setConfig(c => ({ ...c, difficulty: d }))}
                className={cn("flex-1 py-2 rounded-lg text-xs font-medium border transition-all capitalize",
                  config.difficulty === d ? "bg-brand border-brand text-white" : "border-surface-border text-gray-400")}>
                {d}
              </button>
            ))}
          </div>
        </div>

        <div>
          <label className="block text-xs text-gray-400 mb-1.5">Company Context (optional)</label>
          <input className="input-dark" placeholder="e.g. Amazon, TCS, Google…"
            value={config.company_context ?? ""}
            onChange={e => setConfig(c => ({ ...c, company_context: e.target.value || undefined }))} />
        </div>

        <div className="bg-amber-400/10 border border-amber-400/20 rounded-xl p-3 text-xs text-amber-300">
          ⚠️ Anti-cheat: Tab switching is detected and penalised (-2% per switch after 3).
          Auto-submit when time expires.
        </div>

        <button onClick={startExam} disabled={loading || config.domains.length === 0} className="btn-primary w-full">
          {loading ? "Generating questions with AI…" : "🚀 Start Exam"}
        </button>
      </div>

      {/* History */}
      {history.length > 0 && (
        <div className="glass-card p-5">
          <h3 className="text-sm font-semibold text-white mb-3">Recent Attempts</h3>
          <div className="space-y-2">
            {history.slice(0, 5).map((h: any) => (
              <div key={h.id} className="flex items-center justify-between text-xs py-1 border-b border-surface-border last:border-0">
                <span className="text-gray-400">{new Date(h.created_at).toLocaleDateString()}</span>
                <span className="text-white font-semibold">{h.correct}/{h.total}</span>
                <span className={cn("font-bold", h.score >= 70 ? "text-emerald-400" : h.score >= 50 ? "text-amber-400" : "text-rose-400")}>
                  {h.score?.toFixed(1)}%
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );

  // ── EXAM PHASE ─────────────────────────────────────────────────────────────
  if (phase === "exam" && attempt) {
    const q = attempt.questions[currentQ];
    const total = attempt.questions.length;
    const progress = (currentQ / total) * 100;
    const answered = Object.keys(answers).length;
    const urgent = timeLeft <= 120;

    return (
      <div className="max-w-2xl space-y-4">
        {/* Top bar */}
        <div className="glass-card p-4 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <span className="text-xs text-gray-400">Q {currentQ + 1}/{total}</span>
            <div className="w-32 h-1.5 bg-surface rounded-full overflow-hidden">
              <div className="h-full bg-brand-gradient rounded-full transition-all" style={{ width: `${progress}%` }} />
            </div>
            <span className="text-xs text-gray-400">{answered} answered</span>
          </div>
          <div className={cn("font-mono font-bold text-sm px-3 py-1 rounded-lg",
            urgent ? "text-rose-400 bg-rose-400/10 animate-pulse-slow" : "text-white bg-surface")}>
            ⏱ {fmtSecs(timeLeft)}
          </div>
          {tabSwitches > 0 && (
            <span className="text-xs text-amber-400 bg-amber-400/10 px-2 py-1 rounded-lg">
              ⚠️ {tabSwitches} switch{tabSwitches > 1 ? "es" : ""}
            </span>
          )}
        </div>

        {/* Question */}
        <AnimatePresence mode="wait">
          <motion.div key={q.id} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }} className="glass-card p-6 space-y-5">
            <div className="flex items-start gap-3">
              <span className={cn("text-xs px-2 py-1 rounded-full font-medium shrink-0 mt-0.5",
                q.difficulty === "hard" ? "bg-rose-400/10 text-rose-300" :
                q.difficulty === "medium" ? "bg-amber-400/10 text-amber-300" : "bg-emerald-400/10 text-emerald-300")}>
                {q.difficulty} · {q.domain}
              </span>
              <p className="text-white text-sm leading-relaxed font-medium">{q.question}</p>
            </div>

            <div className="space-y-2">
              {q.options.map(opt => {
                const selected = answers[q.id] === opt.key;
                return (
                  <button key={opt.key} onClick={() => setAnswers(a => ({ ...a, [q.id]: opt.key }))}
                    className={cn("w-full text-left px-4 py-3 rounded-xl border text-sm transition-all",
                      selected
                        ? "border-brand bg-brand/15 text-white"
                        : "border-surface-border text-gray-300 hover:border-brand/40 hover:bg-white/5")}>
                    <span className={cn("font-bold mr-2", selected ? "text-brand" : "text-gray-500")}>{opt.key}.</span>
                    {opt.text}
                  </button>
                );
              })}
            </div>
          </motion.div>
        </AnimatePresence>

        {/* Navigation */}
        <div className="flex justify-between gap-3">
          <button disabled={currentQ === 0} onClick={() => setCurrentQ(n => n - 1)}
            className="px-4 py-2 rounded-xl border border-surface-border text-sm text-gray-400 hover:text-white disabled:opacity-40 transition-all">
            ← Prev
          </button>

          {/* Question dots */}
          <div className="flex gap-1 flex-wrap justify-center flex-1">
            {attempt.questions.map((_, i) => (
              <button key={i} onClick={() => setCurrentQ(i)}
                className={cn("w-6 h-6 rounded-full text-xs font-medium transition-all",
                  i === currentQ ? "bg-brand text-white" :
                  answers[attempt.questions[i].id] ? "bg-emerald-400/20 text-emerald-400 border border-emerald-400/40" :
                  "bg-surface text-gray-500 border border-surface-border")}>
                {i + 1}
              </button>
            ))}
          </div>

          {currentQ < total - 1
            ? <button onClick={() => setCurrentQ(n => n + 1)}
                className="px-4 py-2 rounded-xl border border-surface-border text-sm text-gray-400 hover:text-white transition-all">
                Next →
              </button>
            : <button onClick={() => handleSubmit(false)} disabled={loading}
                className="btn-primary px-4 py-2 text-sm">
                {loading ? "Submitting…" : "Submit Exam ✓"}
              </button>
          }
        </div>
      </div>
    );
  }

  // ── RESULT PHASE ───────────────────────────────────────────────────────────
  if (phase === "result" && result) {
    const grade = result.score >= 80 ? "Excellent" : result.score >= 60 ? "Good" : result.score >= 45 ? "Average" : "Needs Work";
    const gradeColor = result.score >= 80 ? "text-emerald-400" : result.score >= 60 ? "text-blue-400" : result.score >= 45 ? "text-amber-400" : "text-rose-400";

    return (
      <div className="max-w-3xl space-y-5">
        <div className="glass-card p-8 text-center">
          <p className="text-6xl font-black mb-2">
            <span className={gradeColor}>{result.score.toFixed(1)}%</span>
          </p>
          <p className={cn("text-xl font-bold mb-1", gradeColor)}>{grade}</p>
          <p className="text-gray-400 text-sm">{result.correct}/{result.total} correct · {fmtSecs(result.time_taken_seconds)}</p>
          <p className="text-xs text-gray-500 mt-1">{result.rank_estimate}</p>
          {tabSwitches > 0 && (
            <p className="text-xs text-amber-400 mt-2">⚠️ {tabSwitches} tab switch penalty applied</p>
          )}
        </div>

        <div className="grid grid-cols-2 gap-4">
          {Object.entries(result.domain_breakdown).map(([domain, stats]) => (
            <div key={domain} className="glass-card p-4">
              <p className="text-xs text-gray-400 mb-1">{domain}</p>
              <p className="text-white font-semibold">{stats.correct}/{stats.total}</p>
              <div className="h-1.5 bg-surface rounded-full mt-2 overflow-hidden">
                <div className="h-full bg-brand-gradient rounded-full"
                  style={{ width: `${stats.total ? stats.correct / stats.total * 100 : 0}%` }} />
              </div>
            </div>
          ))}
        </div>

        {result.weak_areas.length > 0 && (
          <div className="glass-card p-5">
            <h3 className="text-sm font-semibold text-white mb-2">📚 Weak Areas to Focus On</h3>
            <div className="flex flex-wrap gap-2">
              {result.weak_areas.map(a => (
                <span key={a} className="text-xs px-2 py-1 bg-rose-400/10 text-rose-300 border border-rose-400/20 rounded-lg">{a}</span>
              ))}
            </div>
          </div>
        )}

        {/* Q&A review */}
        <div className="glass-card p-5 space-y-3">
          <h3 className="text-sm font-semibold text-white">Review Answers</h3>
          {result.question_results.map((qr, i) => (
            <div key={i} className={cn("rounded-xl p-3 border text-xs",
              qr.is_correct ? "bg-emerald-400/5 border-emerald-400/20" : "bg-rose-400/5 border-rose-400/20")}>
              <p className="text-white mb-1 font-medium">{i + 1}. {qr.question.slice(0, 120)}{qr.question.length > 120 ? "…" : ""}</p>
              <p className={qr.is_correct ? "text-emerald-400" : "text-rose-400"}>
                {qr.is_correct ? "✅ Correct" : `❌ You: ${qr.selected || "skipped"} · Correct: ${qr.correct}`}
              </p>
              {!qr.is_correct && qr.explanation && (
                <p className="text-gray-400 mt-1">{qr.explanation}</p>
              )}
            </div>
          ))}
        </div>

        <button onClick={() => { setPhase("config"); setResult(null); }} className="btn-primary w-full">
          Take Another Exam
        </button>
      </div>
    );
  }

  return null;
}
